In [16]:
import pp

In [32]:
def pprint(x,index):
    for i in range(index):
        name = x +str(i+1)
        
        print(name+"输出结果为: \n",eval(name),'\n')
        
# 发现一个问题，直接通过模块调用函数的方法行不通
#因为跨文件的时候函数内部不能使用全局变量

# 功能

处理和存储大型矩阵。

##  基本操作

创建数组

方法一

In [1]:

import numpy as np 

l = list(range(1,10,2)) # 先创建个列表
l

[1, 3, 5, 7, 9]

In [2]:
arr = np.array(l) # 转成array 
arr

array([1, 3, 5, 7, 9])

In [3]:
type(arr)  # 看一下数据类型

numpy.ndarray

方法二

In [41]:
import numpy as np 
a1 = np.ones(10)  # 全1 指定10个
a2 = np.zeros(10) # 全0 指定10个
a3 = np.full(shape = [2,3],fill_value = 2.718) # 2行3列 指定元素是2.718
a4 = np.arange(start = 0 ,stop = 20,step = 2) # 等差数列 步长是2
a5 = np.linspace(start = 0 , stop = 9 ,num = 3) # num决定了有几个元素
a6 = np.random.randint(0,100,size = 10) # 随机整数 指定个数是10
a7 = np.random.randn(5) # 正态分布
a8 = np.random.random(size = 5) #随机浮点 指定个数是5 

pprint('a',8)

a1输出结果为: 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

a2输出结果为: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

a3输出结果为: 
 [[2.718 2.718 2.718]
 [2.718 2.718 2.718]] 

a4输出结果为: 
 [ 0  2  4  6  8 10 12 14 16 18] 

a5输出结果为: 
 [0.  4.5 9. ] 

a6输出结果为: 
 [73 38 14 79 68 79 55 87 44 39] 

a7输出结果为: 
 [-0.23729201 -0.56697742  1.56617739 -0.41276923  0.06499482] 

a8输出结果为: 
 [0.65660321 0.05895132 0.60870573 0.70013534 0.47556808] 



查看数组

In [44]:
import numpy as np 
arr = np.random.randint(0,100,size=(3,4,5)) # 3个4行5列
arr

array([[[50, 76, 59, 31, 10],
        [26, 45, 40, 46, 59],
        [74,  2, 40, 90, 13],
        [54, 82, 74, 17, 98]],

       [[86, 34, 83, 81, 38],
        [25, 86, 70, 53, 51],
        [43, 32, 60, 53, 99],
        [12, 85, 44, 10, 23]],

       [[57, 19, 48, 20, 42],
        [18, 16, 99,  2, 94],
        [ 6, 82, 30, 84, 32],
        [71, 59, 22, 71, 24]]])

In [45]:
v1 = arr.ndim # 数组维度
v2 = arr.shape #尺寸形状 3个4行5列
v3 = arr.size  # 元素总个数
v4 = arr.dtype #数组元素的类型  注意了 这个地方可以看到 array里的所有元素类型要一致
v5 = arr.itemsize # 数据类型是int64 ， 一个字节8位  64/8 = 8

pprint('v',5)

v1输出结果为: 
 3 

v2输出结果为: 
 (3, 4, 5) 

v3输出结果为: 
 60 

v4输出结果为: 
 int64 

v5输出结果为: 
 8 



文件IO （存取

存一个array 用 save , 存多个array 用savez

In [51]:
x = np.random.randn(5)
y = np.arange(0,10,2) # 0-9 跨度是2 

np.save('x_arr.npy',x)
np.savez('xy_array.npz',xarr = x, yarr = y)

取都用load 

In [53]:
np.load('x_arr.npy')

array([-1.1574776 ,  1.91279839, -0.18512853,  0.45573406,  0.22466963])

In [54]:
np.load('xy_array.npz')

In [55]:
xc = np.load('xy_array.npz')

xc['yarr'] # 读取类似字典


array([0, 2, 4, 6, 8])

读写 csv,txt文件

In [58]:
arr = np.random.randint(0,10,size = (3,4))
arr

array([[6, 9, 4, 3],
       [9, 6, 7, 1],
       [4, 8, 2, 6]])

In [61]:
#存
np.savetxt('arr.csv',arr,delimiter = ',')
#取
np.loadtxt('arr.csv',delimiter = ',',dtype=np.int32)


array([[6, 9, 4, 3],
       [9, 6, 7, 1],
       [4, 8, 2, 6]], dtype=int32)

In [62]:
#存
np.savetxt('arr.txt',arr,delimiter = ',')
#取
np.loadtxt('arr.txt',delimiter = ',',dtype=np.int32)

array([[6, 9, 4, 3],
       [9, 6, 7, 1],
       [4, 8, 2, 6]], dtype=int32)

# 数据类型

int: int8、uint8、int16、int32、int64 

float: float16、float32、float64

str

In [63]:
import numpy as np 
np.array([1,2,5,8,2],dtype = 'float32')


array([1., 2., 5., 8., 2.], dtype=float32)

In [64]:
arr = list(range(5))
arr

[0, 1, 2, 3, 4]

In [66]:
np.asarray(arr,dtype = 'float32') # asarray 转换时指定类型

array([0., 1., 2., 3., 4.], dtype=float32)

In [68]:
k1 = np.asarray(arr,dtype = 'float32')
k1.astype('int32') # astype 直接换类型

array([0, 1, 2, 3, 4], dtype=int32)

# 数组运算

In [73]:
import numpy as np 
arr1 = np.random.randint(0,10,size = 10)
arr2 = np.random.randint(0,10,size = 10)
print(arr1,'\n',arr2)

[3 4 0 6 9 5 1 0 1 6] 
 [3 1 7 5 0 6 4 6 7 0]


In [75]:
r1 = arr1 - arr2 
r2 = arr1 * arr2 
r3 = arr1 / arr2 
r4 = arr1 ** arr2 
# 全部都是元素一对一的计算 一个萝卜一个坑
pprint('r',4)

r1输出结果为: 
 [ 0  3 -7  1  9 -1 -3 -6 -6  6] 

r2输出结果为: 
 [ 9  4  0 30  0 30  4  0  7  0] 

r3输出结果为: 
 [1.         4.         0.         1.2               inf 0.83333333
 0.25       0.         0.14285714        inf] 

r4输出结果为: 
 [   27     4     0  7776     1 15625     1     0     1     1] 



/Users/jiajia/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [77]:
print(arr1)
print(arr2)
x1 = arr1 < 5 
x2 = arr1 >= 5
x3 = arr1 == 5 
x4 = arr1 == arr2 
x5 = arr1 > arr2 
pprint('x',5)

#也都是一对一的逻辑运算

[3 4 0 6 9 5 1 0 1 6]
[3 1 7 5 0 6 4 6 7 0]
x1输出结果为: 
 [ True  True  True False False False  True  True  True False] 

x2输出结果为: 
 [False False False  True  True  True False False False  True] 

x3输出结果为: 
 [False False False False False  True False False False False] 

x4输出结果为: 
 [ True False False False False False False False False False] 

x5输出结果为: 
 [False  True False  True  True False False False False  True] 



In [79]:
print(arr1)
b1 = 1 / arr1
b2 = arr1 + 5
b3 = arr1 * 5

pprint('b',3)

#广播机制，一荣俱荣

[3 4 0 6 9 5 1 0 1 6]
b1输出结果为: 
 [0.33333333 0.25              inf 0.16666667 0.11111111 0.2
 1.                inf 1.         0.16666667] 

b2输出结果为: 
 [ 8  9  5 11 14 10  6  5  6 11] 

b3输出结果为: 
 [15 20  0 30 45 25  5  0  5 30] 



/Users/jiajia/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [80]:
#也可以
arr1 += 7
arr1
# 不支持/=


array([10, 11,  7, 13, 16, 12,  8,  7,  8, 13])

# 复制和视图

In [83]:
import numpy as np 
a = np.random.randint(1,100,size=(4,5)) # 1-100 整数 四行五列
print(a,'\n')
b = a 
print(b,'\n')
a += 5
print(a,'\n')
print(b,'\n')

# 这个和列表一样 赋值一起变

[[23 52 85 25 24]
 [14 34 40 76 83]
 [87 65 57 96 55]
 [94 40 23 66 99]] 

[[23 52 85 25 24]
 [14 34 40 76 83]
 [87 65 57 96 55]
 [94 40 23 66 99]] 

[[ 28  57  90  30  29]
 [ 19  39  45  81  88]
 [ 92  70  62 101  60]
 [ 99  45  28  71 104]] 

[[ 28  57  90  30  29]
 [ 19  39  45  81  88]
 [ 92  70  62 101  60]
 [ 99  45  28  71 104]] 



In [84]:
display(a,b) # display 也可以打印

array([[ 28,  57,  90,  30,  29],
       [ 19,  39,  45,  81,  88],
       [ 92,  70,  62, 101,  60],
       [ 99,  45,  28,  71, 104]])

array([[ 28,  57,  90,  30,  29],
       [ 19,  39,  45,  81,  88],
       [ 92,  70,  62, 101,  60],
       [ 99,  45,  28,  71, 104]])

In [85]:
# copy 还是好用的

import numpy as np 
a = np.random.randint(0,100,size = (4,5))
b = a.copy()
b is a 
b.base is a 
b.flags.owndata
b.flags.owndata
a += 5 
display(a,b)

#各过各的

array([[37, 99, 88, 41, 71],
       [41, 49, 79, 15,  8],
       [11, 36, 33, 96, 70],
       [15, 26, 95, 91, 38]])

array([[32, 94, 83, 36, 66],
       [36, 44, 74, 10,  3],
       [ 6, 31, 28, 91, 65],
       [10, 21, 90, 86, 33]])

In [91]:
#场景 大批量数据抽样 然后留下样本 删掉占地方的源数据 这个时候要copy 深拷贝

import numpy as np 
a = np.arange(1e8)
a.size

100000000

In [92]:
b = a[::1000000].copy() # 保留抽样数据
b.size

100

In [93]:
del a  # 删掉占地方的源数据

# 索引 切片 迭代

In [97]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
d1 = arr2d[0,2] # 输出（0,2) 
d2 = arr2d[-1,-3] # (1,0)
d3 = arr2d[:2,1:] # 前两行，后两列
d4 = arr2d[:2,-2:] #前两行 后两列

pprint('d',4)

#本质还是列表切片

d1输出结果为: 
 3 

d2输出结果为: 
 7 

d3输出结果为: 
 [[2 3]
 [5 6]] 

d4输出结果为: 
 [[2 3]
 [5 6]] 



## 花式索引

整数数组进行索引叫花式索引 把切下来的数据放到新数组

In [107]:
list1 = list(range(10))
list1.reverse()
arr1 = np.array(list1)
arr1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [5]:
import numpy as np 
arr1 = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
arr1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [108]:
arr1[1]

8

In [2]:
lix1 = [1,2,3,4]
lix1[[1,2]]

TypeError: list indices must be integers or slices, not list

In [110]:
arr1[[2,3,4]] # 可以按索引取值

array([7, 6, 5])

In [7]:
arr2d = np.random.randint(0,50,size = (4,5))
arr2d

array([[40, 37, 34, 18, 46],
       [33, 13, 44, 42,  9],
       [ 8, 26, 48, 40, 26],
       [23,  0, 45, 34, 22]])

In [113]:
arr2d[[1,3]] # 取第2行和第4行

array([[11, 36, 44, 17, 24],
       [ 5, 48,  4, 31, 14]])

In [115]:
arr2d[[1,3],[2]] # 取第2行和第4行 然后取第3列

array([44,  4])

In [23]:
arr2d[[2],[1,2,1]] # 取第2行和第4行 然后取2行3列， 4行4列

array([26, 48, 26])

In [25]:
arr2d[:3,[2,0]] 

array([[34, 40],
       [44, 33],
       [48,  8]])

In [134]:
print(arr2d)
f1 = arr2d[1][2] # LC + L 
f2 = arr2d[[1,2]][0] # A + L 
f3 = arr2d[[1,2]][1] # A + L 
f4 = arr2d[[1,2]][1][2] # A + L + L 

f5 = arr2d[np.ix_([1,2],[1,0])] # 取(1,1)(1,0)(2,1)(2,0)
f6 = arr2d[[1,2]][1,2] # A + LC
f7 = arr2d[[1,2]][:,2] # A + LC

pprint('f',7)

#本质还是列表叠加

[[29 34 14 40 36]
 [11 36 44 17 24]
 [39 12 39 10 42]
 [ 5 48  4 31 14]]
f1输出结果为: 
 44 

f2输出结果为: 
 [11 36 44 17 24] 

f3输出结果为: 
 [39 12 39 10 42] 

f4输出结果为: 
 39 

f5输出结果为: 
 [[36 11]
 [12 39]] 

f6输出结果为: 
 39 

f7输出结果为: 
 [44 39] 



In [34]:
print(arr2d)

d1 = arr2d[1,2] # 取 (1,2)
d2 = arr2d[:2,3] # 取 (0,3)(1,3)
d3 = arr2d[:2,3:] # 取 (0,3)(0,4)(1,3)(1,4)
d4 = arr2d[2] # 取 (2,0)(2,1)(2,2)(2,3)(2,4) # 一个参数的时候默认是第x行
pprint('d',4)

[[40 37 34 18 46]
 [33 13 44 42  9]
 [ 8 26 48 40 26]
 [23  0 45 34 22]]
d1输出结果为: 
 44 

d2输出结果为: 
 [18 42] 

d3输出结果为: 
 [[18 46]
 [42  9]] 

d4输出结果为: 
 [ 8 26 48 40 26] 



In [36]:
arr3d = np.random.randint(0,50,size = 90).reshape(3,5,6)
arr3d

array([[[41,  3, 37, 25,  1, 46],
        [12, 49, 43,  8,  3, 43],
        [ 4, 23, 38, 48, 12,  4],
        [20, 40, 15, 35,  6,  1],
        [ 3, 36, 32, 36, 14,  1]],

       [[16, 39, 46, 31, 17, 24],
        [19, 48, 19, 16, 25, 40],
        [16, 25, 11,  5, 24, 23],
        [36, 31,  2, 37, 11, 12],
        [40, 15, 32, 42,  1,  0]],

       [[19, 10, 11, 46, 20, 49],
        [20, 42, 10,  5, 47, 32],
        [49, 29, 12, 43, 27, 28],
        [38, 21,  7, 17, 43, 23],
        [ 3, 19, 39, 28, 19, 47]]])

In [47]:
print(arr3d)
d1 = arr3d[2,1:,3:] # 选第3个矩阵，取包括2行所有行 取包括4列所有列
d2 = arr3d[[1,2]]   # 选第2个和第3个矩阵
d3 = arr3d[[1,2]][1] # 选第2个矩阵和第3个矩阵，再从这两个里 选后一个矩阵
d4 = arr3d[[1,2],[1,2],[2]] # (1,1,2) (2,2,2)
pprint('d',4)

[[[41  3 37 25  1 46]
  [12 49 43  8  3 43]
  [ 4 23 38 48 12  4]
  [20 40 15 35  6  1]
  [ 3 36 32 36 14  1]]

 [[16 39 46 31 17 24]
  [19 48 19 16 25 40]
  [16 25 11  5 24 23]
  [36 31  2 37 11 12]
  [40 15 32 42  1  0]]

 [[19 10 11 46 20 49]
  [20 42 10  5 47 32]
  [49 29 12 43 27 28]
  [38 21  7 17 43 23]
  [ 3 19 39 28 19 47]]]
d1输出结果为: 
 [[ 5 47 32]
 [43 27 28]
 [17 43 23]
 [28 19 47]] 

d2输出结果为: 
 [[[16 39 46 31 17 24]
  [19 48 19 16 25 40]
  [16 25 11  5 24 23]
  [36 31  2 37 11 12]
  [40 15 32 42  1  0]]

 [[19 10 11 46 20 49]
  [20 42 10  5 47 32]
  [49 29 12 43 27 28]
  [38 21  7 17 43 23]
  [ 3 19 39 28 19 47]]] 

d3输出结果为: 
 [[19 10 11 46 20 49]
 [20 42 10  5 47 32]
 [49 29 12 43 27 28]
 [38 21  7 17 43 23]
 [ 3 19 39 28 19 47]] 

d4输出结果为: 
 [19 12] 



## 布尔值索引

In [135]:
names = np.array(['softpo','Brandon','Will','Michael','Will','Ella','Daniel','softpo',' Will','Brandon'])
cond1 = names =='Will'
cond1

array([False, False,  True, False,  True, False, False, False, False,
       False])

In [136]:
names[cond1] # 只输出TRUE

array(['Will', 'Will'], dtype='<U7')

In [140]:
arr = np.random.randint(0,100,size = (10,8))
print(arr)
cond2 = arr > 90
cond2

[[58 58  4 63 15 51  4 30]
 [17  2 84 23 97 57  8 57]
 [66 29 52 91 19 28 67 32]
 [99 14  1 14 51 57 74 17]
 [68 62 99 98 75 30 81 63]
 [15 26 86 79 60 20 79 69]
 [91 50 18  5 40 54 12 46]
 [92 46 65 81 78 28 74 30]
 [58  0 73 76 98 62 45 21]
 [83 38 52 28 83  7 47 65]]


array([[False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [ True, False, False, False, False, False, False, False],
       [False, False,  True,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [139]:
arr[cond2]

array([95, 96, 96, 92, 93, 97, 97, 97, 96])

# 形状操作

In [148]:
import numpy as np 

ar1 = np.random.randint(0,10,size = (3,4,5)) # 就算形状变了 综述也要是3*4*5  =60 
ar2 = ar1.reshape(12,5)
ar3 = ar1.reshape(-1,5)  # 这里-1 是不知道，看着办的意思，只能这么搞一个，两个都不知道就没法搞了
ar4 = ar1.reshape(12,-1)
ar5 = ar1.reshape(60,1)

pprint('ar',5)

ar1输出结果为: 
 [[[9 3 6 6 3]
  [3 1 9 8 8]
  [6 6 7 5 2]
  [5 9 4 3 1]]

 [[9 2 8 8 5]
  [4 9 8 8 8]
  [6 2 1 4 7]
  [7 6 3 8 3]]

 [[2 1 3 9 5]
  [0 3 1 8 9]
  [6 6 1 2 6]
  [4 6 1 0 7]]] 

ar2输出结果为: 
 [[9 3 6 6 3]
 [3 1 9 8 8]
 [6 6 7 5 2]
 [5 9 4 3 1]
 [9 2 8 8 5]
 [4 9 8 8 8]
 [6 2 1 4 7]
 [7 6 3 8 3]
 [2 1 3 9 5]
 [0 3 1 8 9]
 [6 6 1 2 6]
 [4 6 1 0 7]] 

ar3输出结果为: 
 [[9 3 6 6 3]
 [3 1 9 8 8]
 [6 6 7 5 2]
 [5 9 4 3 1]
 [9 2 8 8 5]
 [4 9 8 8 8]
 [6 2 1 4 7]
 [7 6 3 8 3]
 [2 1 3 9 5]
 [0 3 1 8 9]
 [6 6 1 2 6]
 [4 6 1 0 7]] 

ar4输出结果为: 
 [[9 3 6 6 3]
 [3 1 9 8 8]
 [6 6 7 5 2]
 [5 9 4 3 1]
 [9 2 8 8 5]
 [4 9 8 8 8]
 [6 2 1 4 7]
 [7 6 3 8 3]
 [2 1 3 9 5]
 [0 3 1 8 9]
 [6 6 1 2 6]
 [4 6 1 0 7]] 

ar5输出结果为: 
 [[9]
 [3]
 [6]
 [6]
 [3]
 [3]
 [1]
 [9]
 [8]
 [8]
 [6]
 [6]
 [7]
 [5]
 [2]
 [5]
 [9]
 [4]
 [3]
 [1]
 [9]
 [2]
 [8]
 [8]
 [5]
 [4]
 [9]
 [8]
 [8]
 [8]
 [6]
 [2]
 [1]
 [4]
 [7]
 [7]
 [6]
 [3]
 [8]
 [3]
 [2]
 [1]
 [3]
 [9]
 [5]
 [0]
 [3]
 [1]
 [8]
 [9]
 [6]
 [6]
 [1]
 [2]
 [6]
 [4]
 [6]
 [

In [153]:
print(ar1.shape)
print(np.transpose(ar1).shape)
print(np.transpose(ar1,axes=(2,0,1)).shape)

(3, 4, 5)
(5, 4, 3)
(5, 3, 4)


In [152]:
ar2 =np.random.randint(0,10,size=(3,4))
print(ar2)
np.transpose(ar2)  #转置


[[1 8 6 0]
 [9 7 4 6]
 [7 0 8 6]]


array([[1, 9, 7],
       [8, 7, 0],
       [6, 4, 8],
       [0, 6, 6]])

合成

In [155]:
import numpy as np 
ar1  = np.array([[1,2,3]])
ar2  = np.array([[4,5,6]])
display(ar1,ar2)

array([[1, 2, 3]])

array([[4, 5, 6]])

In [158]:
np.concatenate([ar1,ar2],axis = 0) # 竖着


array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
np.concatenate([ar1,ar2],axis = 1) # 横着

array([[1, 2, 3, 4, 5, 6]])

In [162]:
np.hstack((ar1,ar2))  # horizion

array([[1, 2, 3, 4, 5, 6]])

In [161]:
np.vstack((ar1,ar2))  #vertical 

array([[1, 2, 3],
       [4, 5, 6]])

拆分

In [163]:
import numpy as np

arr = np.random.randint(0,10,size=(6,5))
arr

array([[5, 1, 7, 8, 8],
       [9, 0, 9, 2, 9],
       [1, 0, 3, 3, 0],
       [9, 1, 3, 7, 9],
       [6, 8, 7, 0, 2],
       [9, 0, 1, 5, 5]])

In [168]:
s  = np.split(arr,indices_or_sections =2 ,axis = 0) # 横切
print(s[0],'\n','\n',s[1])

[[5 1 7 8 8]
 [9 0 9 2 9]
 [1 0 3 3 0]] 
 
 [[9 1 3 7 9]
 [6 8 7 0 2]
 [9 0 1 5 5]]


In [171]:
s  = np.split(arr,indices_or_sections =[2,3] ,axis = 1) # 纵切 断点为2,3
print(s[0],'\n','\n',s[1],'\n','\n',s[2])

[[5 1]
 [9 0]
 [1 0]
 [9 1]
 [6 8]
 [9 0]] 
 
 [[7]
 [9]
 [3]
 [3]
 [7]
 [1]] 
 
 [[8 8]
 [2 9]
 [3 0]
 [7 9]
 [0 2]
 [5 5]]


In [173]:
s = np.vsplit(arr,indices_or_sections=3) # 一样的 横切
print(s[0],'\n','\n',s[1],'\n','\n',s[2])

[[5 1 7 8 8]
 [9 0 9 2 9]] 
 
 [[1 0 3 3 0]
 [9 1 3 7 9]] 
 
 [[6 8 7 0 2]
 [9 0 1 5 5]]


In [174]:
np.hsplit(arr,indices_or_sections=[1,4]) # 竖切

[array([[5],
        [9],
        [1],
        [9],
        [6],
        [9]]), array([[1, 7, 8],
        [0, 9, 2],
        [0, 3, 3],
        [1, 3, 7],
        [8, 7, 0],
        [0, 1, 5]]), array([[8],
        [9],
        [0],
        [9],
        [2],
        [5]])]

# 广播

In [176]:
import numpy as np 
ar1  = np.sort(np.array([0,1,2,3]*3))
ar2  = ar1.reshape(4,3)
ar3  = np.array([1,2,3]) 
ar4  = ar2 + ar3 

pprint('ar',4)

# 4*3 和 1*3 能加的原因是 第二个从上到下卷了四遍 

ar1输出结果为: 
 [0 0 0 1 1 1 2 2 2 3 3 3] 

ar2输出结果为: 
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]] 

ar3输出结果为: 
 [1 2 3] 

ar4输出结果为: 
 [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]] 



In [184]:
a1 = np.zeros(9).reshape(3,3)
a2 = np.ones(3).reshape(3,1)
a3 = a1+a2 
pprint('a',3) # 同样的道理，从左往右卷了3遍

a1输出结果为: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

a2输出结果为: 
 [[1.]
 [1.]
 [1.]] 

a3输出结果为: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 



三维数组广播

In [186]:
import numpy as np 

ar1 = np.array(list(range(10))*3).reshape(3,2,5)
ar2 = np.ones(10).reshape(2,5)
ar3 = ar1 + ar2 

pprint('ar',3)

#又广播了
#只要有一个维度是可以走的 就可以传播

ar1输出结果为: 
 [[[0 1 2 3 4]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]] 

ar2输出结果为: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

ar3输出结果为: 
 [[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]]

 [[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]]

 [[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]]] 



# 通用函数


abs、sqrt、square、exp、log、sin、cos、tan，maxinmum、minimum、all、any、inner、clip、 round、trace、ceil、floor

## 函数

In [191]:
import numpy as np 
x = np.array(list(range(6))).reshape(3,2)
y = list(range(6))
y.reverse()
y = np.array(y).reshape(2,3)
display(x,y)

array([[0, 1],
       [2, 3],
       [4, 5]])

array([[5, 4, 3],
       [2, 1, 0]])

In [193]:
#点乘和叉乘
x @ y  #矩阵乘法 点乘

array([[ 2,  1,  0],
       [16, 11,  6],
       [30, 21, 12]])

In [194]:
np.dot(x,y) # 一样的

array([[ 2,  1,  0],
       [16, 11,  6],
       [30, 21, 12]])

叉乘和内积说的都是元素一对一计算

## where

In [195]:
cond = np.array([True,False,True])
arr1 = np.array([1,2,3])
arr2 = np.array([7,8,9])
np.where(cond,arr1,arr2)

array([1, 8, 3])

In [196]:
arr3 = np.random.randint(0,30,size=20)
np.where(arr3 < 15 , arr3 , -15) # 小于15的全变成 -15 

array([-15, -15, -15,   1,   5,   6,   3, -15, -15, -15, -15, -15, -15,
         5,   0, -15, -15,   7,  11,   3])

## 排序

In [200]:
arr  = np.random.randint(0,10,size=5)
arr
a  = arr.copy()

In [203]:
a.sort()
a1 = a 
a2 = np.sort(arr)

a3 = arr.argsort() # 排序后的索引

pprint('a',3)
print('arr',arr)

a1输出结果为: 
 [1 1 3 4 5] 

a2输出结果为: 
 [1 1 3 4 5] 

a3输出结果为: 
 [1 4 3 2 0] 

arr [5 1 4 3 1]


## 集合运算

In [206]:
 
A = np.array([2,4,6,8])
B = np.array([3,4,5,6])
s1 = np.intersect1d(A,B) # 交集
s2 = np.union1d(A,B) # 并集 
s3 = np.setdiff1d(A,B) #差集，A中有，B中没有 array([2, 8])

display(A,B)
pprint('s',3)


array([2, 4, 6, 8])

array([3, 4, 5, 6])

s1输出结果为: 
 [4 6] 

s2输出结果为: 
 [2 3 4 5 6 8] 

s3输出结果为: 
 [2 8] 



## 数学 统计函数

min、max、mean、median、sum、std、var、cumsum、cumprod、argmin、argmax、 argwhere、cov、corrcoef

In [208]:
import numpy as np 

arr  = np.random.randint(0,10,size = (2,3))
print(arr)
a1 = arr.min() # min
a2 = arr.argmax() # max的索引
a3 = np.argwhere(arr > 20) # >20的元素的索引
a4 = np.cumsum(arr) # 累加 9 ,9+7,9+7+9,...
a5 = arr.mean(axis = 0) # 竖着求均值
a6 = arr.mean(axis = 1) #横着求
a7 = np.cov(arr,rowvar = True) # 协方差矩阵
a8 = np.corrcoef(arr,rowvar = True) # 相关性系数

pprint('a',8)

[[9 7 9]
 [4 3 5]]
a1输出结果为: 
 3 

a2输出结果为: 
 0 

a3输出结果为: 
 [] 

a4输出结果为: 
 [ 9 16 25 29 32 37] 

a5输出结果为: 
 [6.5 5.  7. ] 

a6输出结果为: 
 [8.33333333 4.        ] 

a7输出结果为: 
 [[1.33333333 1.        ]
 [1.         1.        ]] 

a8输出结果为: 
 [[1.        0.8660254]
 [0.8660254 1.       ]] 



## 线性代数

In [212]:
# 点乘  @ 或者 np.dot(x,y)之前演示过了

A = np.random.randint(0,10,size = (3,3))
print(A)

from numpy.linalg import inv,det,eig,qr,svd

t1 = inv(A) # 逆
t2 = det(A) # 行列式
t3 = eig(A) #特征值 特征向量
t4 = qr(A)  # qr分解值
t5 = svd(A) # svd分解值

pprint('t',5)


[[8 8 4]
 [3 3 6]
 [9 4 5]]
t1输出结果为: 
 [[-0.05       -0.13333333  0.2       ]
 [ 0.21666667  0.02222222 -0.2       ]
 [-0.08333333  0.22222222  0.        ]] 

t2输出结果为: 
 180.0 

t3输出结果为: 
 (array([16.92389216+0.j        , -0.46194608+3.22838305j,
       -0.46194608-3.22838305j]), array([[ 0.65452285+0.j        , -0.3606994 -0.3903272j ,
        -0.3606994 +0.3903272j ],
       [ 0.41370738+0.j        ,  0.63087194+0.j        ,
         0.63087194-0.j        ],
       [ 0.63280807+0.j        , -0.18365774+0.53461298j,
        -0.18365774-0.53461298j]])) 

t4输出结果为: 
 (array([[-6.44658371e-01, -6.79063998e-01, -3.51123442e-01],
       [-2.41746889e-01, -2.54648999e-01,  9.36329178e-01],
       [-7.25240668e-01,  6.88495442e-01,  8.32667268e-17]]), array([[-12.40967365,  -8.78347031,  -7.65531816],
       [  0.        ,  -3.44247721,  -0.80167278],
       [  0.        ,   0.        ,   4.2134813 ]])) 

t5输出结果为: 
 (array([[-0.68093086,  0.50090386, -0.53425507],
       [-0.37800771, -0.8652

# 案例 鸢尾花

In [216]:
import numpy as np 

data  = np.loadtxt('./iris.csv',delimiter = ',')
print(data.shape)

data.sort(axis=-1)  # 排序 发现不带axis = -1 也能正常排 
print(data)

(150,)
[4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.8 4.8 4.9 4.9
 4.9 4.9 4.9 4.9 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.1 5.1 5.1 5.1
 5.1 5.1 5.1 5.1 5.1 5.2 5.2 5.2 5.2 5.3 5.4 5.4 5.4 5.4 5.4 5.4 5.5 5.5
 5.5 5.5 5.5 5.5 5.5 5.6 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7 5.7 5.7 5.7 5.7
 5.7 5.8 5.8 5.8 5.8 5.8 5.8 5.8 5.9 5.9 5.9 6.  6.  6.  6.  6.  6.  6.1
 6.1 6.1 6.1 6.1 6.1 6.2 6.2 6.2 6.2 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3
 6.4 6.4 6.4 6.4 6.4 6.4 6.4 6.5 6.5 6.5 6.5 6.5 6.6 6.6 6.7 6.7 6.7 6.7
 6.7 6.7 6.7 6.7 6.8 6.8 6.8 6.9 6.9 6.9 6.9 7.  7.1 7.2 7.2 7.2 7.3 7.4
 7.6 7.7 7.7 7.7 7.7 7.9]


In [217]:
print('简单排序后:', data)
print('数据去重后:', np.unique(data)) # 去除重复数据
print('数据求和:', np.sum(data)) # 数组求和
print('元素求累加和', np.cumsum(data)) # 元素求累加和
print('数据的均值:', np.mean(data)) # 均值
print('数据的标准差:', np.std(data)) # 标准差
print('数据的方差:', np.var(data)) # 方差
print('数据的最小值:', np.min(data)) # 最小值
print('数据的最大值:', np.max(data)) # 最大值

简单排序后: [4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.8 4.8 4.9 4.9
 4.9 4.9 4.9 4.9 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.1 5.1 5.1 5.1
 5.1 5.1 5.1 5.1 5.1 5.2 5.2 5.2 5.2 5.3 5.4 5.4 5.4 5.4 5.4 5.4 5.5 5.5
 5.5 5.5 5.5 5.5 5.5 5.6 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7 5.7 5.7 5.7 5.7
 5.7 5.8 5.8 5.8 5.8 5.8 5.8 5.8 5.9 5.9 5.9 6.  6.  6.  6.  6.  6.  6.1
 6.1 6.1 6.1 6.1 6.1 6.2 6.2 6.2 6.2 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3
 6.4 6.4 6.4 6.4 6.4 6.4 6.4 6.5 6.5 6.5 6.5 6.5 6.6 6.6 6.7 6.7 6.7 6.7
 6.7 6.7 6.7 6.7 6.8 6.8 6.8 6.9 6.9 6.9 6.9 7.  7.1 7.2 7.2 7.2 7.3 7.4
 7.6 7.7 7.7 7.7 7.7 7.9]
数据去重后: [4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.
 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6 7.7 7.9]
数据求和: 876.5
元素求累加和 [  4.3   8.7  13.1  17.5  22.   26.6  31.2  35.8  40.4  45.1  49.8  54.6
  59.4  64.2  69.   73.8  78.7  83.6  88.5  93.4  98.3 103.2 108.2 113.2
 118.2 123.2 128.2 133.2 138.2 143.2 148.2 153.2 158.3 163.4 168.5 17